spring:
  application:
    name: ProdutosApi
  datasource:
    url: jdbc:h2:mem:produtos
    username: guda
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
